updating dsink

diff --git a/bin/dsink b/bin/dsink
--- a/bin/dsink
+++ b/bin/dsink
@@ -21,7 +21,6 @@
 set -o errexit
 set -o nounset
 set -o pipefail
-#set -x
 
 # SOURCE DIR NAMES TO MANAGE
 _dsinkSourceDirs=(studio lab office house library)
@@ -33,8 +32,8 @@ _requiredCommands=(rsync cryptsetup lsblk parted wipefs)
 
 # debugging and logging settings
 # script debug toggle (set to true to enable default global debugging)
-_DEBUG=true
-# silent mode for scripting (supresses stdout/stderr)
+_DEBUG=false
+# silent mode for scripting (supresses normal output)
 _SILENT=false
 # logging facility (debug always goes here, unless)
 _LOG=true
@@ -45,6 +44,7 @@ boldred=$(tput bold; tput setaf 1)
 green=$(tput setaf 2)
 cyan=$(tput setaf 6)
 yellow=$(tput setaf 3)
+prompt=$(tput setab 5; tput setaf 7)
 reset=$(tput sgr0)
 
 # DEFAULT SETTINGS
@@ -57,18 +57,33 @@ _logFile="${_dsinkDir}/dsink.log"
 _dsinkCatalog="${_dsinkDir}/dsink.catalog"
 _dsinkMount="${_dsinkDir}/media"
 
+# global variables we use
+# _findNewDisk: declare -g _newDiskDevice
+
+_prompt() {
+	# hack to avoid fixing _log and include a PROMPT type
+	# TODO: add this idea into _log to keep the "universal" claim
+	echo -n "${prompt}USER${reset}: ${1} "
+}
+
 # LOGGING 
 
 _log() {
-	# levels
+	# global prompt and logging function
+	# consults _DEBUG _SILENT and _LOG for behavior
+	# TODO: add type for user PROMPT (ie USER interaction)
+	# TODO: try and optimize...many calls for each log event (although the use
+	# would never be bogged down since this is a single user system)
+	# levels:
 	# 0=debug eg: _log 0 "func(): value x was found and changed into x2"
 	# 1=info eg: _log 1 "main(): set parameters to x y and z"
 	# 2=warn eg: _log 2 "func(): doing y because the force flag was set"
 	# 3=error eg: _log 3 "main(): non-fatal error, will continue trying"
 	# 4=fatal eg: _log 4 "main(): fatal error, quitting"
 	# ARG1 = log level (can be overridden by setting _logLevelOverride)
-	# prints 1-3 no matter what, unless _LOG is false and/or _SILENT is true
-	# set to 0 to force all logs into DEBUG pipe
+	# prints 1-3 no matter what, unless _LOG is false and/or _SILENT is true (and
+	# there are functions (eg _format) that should never be SILENT)
+	# set to 0 to force all logs into DEBUG pipeline
 	local _logLevelOverride=
 	local _logLevel=${_logLevelOverride:-$1}
 	local _logMessage="${@:2}"
@@ -76,11 +91,13 @@ _log() {
 	# set timestamp for log message (unix seconds)
 	local _timeStamp=$(date +%s)
 	# define log levels and colors
+	# TODO: fix this...not using it as designed
 	declare -A _i=([0]=DEBUG [1]=INFO [2]=WARN [3]=ERROR [4]=FATAL)
 	declare -A _c=([0]=cyan [1]=green [2]=yellow [3]=red [4]=boldred)
 	local _level=${_i[${_logLevel}]}
 	local _color=${_c[${_logLevel}]}
 	# check if a logfile exists
+	# this could be a global VAR
 	[ -f "${_logFile}" ] && _canLog=true
 	# if debug is false and message level is 0, stop
 	[  ${_DEBUG} = false ] && [ ${_logLevel} = 0 ] && return
@@ -88,7 +105,14 @@ _log() {
 	[ ${_LOG} = true ] && [ ${_canLog} = true ] && \
 		 printf "%s\n" "${_timeStamp} ${_level}: ${_logMessage}" >> "${_logFile}"
 	# if silent is true, don't print anything to the console and stop
-	[ ${_SILENT} = true ] && return
+	# BUG HERE
+	# if SILENT is true and _log = 4, then we don't exit as expected on FATAL
+	# error
+	if [ ${_SILENT} = true ] && [ ${_logLevel} = 4 ]; then
+		exit 1
+	elif [ ${_SILENT} = true ]; then
+		return
+	fi
 	# if _SILENT is false, prettyPrint to console based on level
 	if [ ! ${_SILENT} = true ]; then
 		[ ${_DEBUG} = true ] && [ ${_logLevel} = 0 ]  && \
@@ -103,6 +127,7 @@ _log() {
 			echo "${boldred}FATAL${reset}: ${_logMessage}" && exit 1
 	fi
 }
+
 
 # HELPER FUNCTIONS
 
@@ -178,9 +203,9 @@ _getOpts () {
 	# export a paired down parameter string flags and args read within this
 	# function will be discarded, leaving behind only that which the rest needs
 	export _workingParams=$*
-	_log 1 "${FUNCNAME[0]}: _LOG=${_LOG}"
-	_log 1 "${FUNCNAME[0]}: _SILENT=${_SILENT}"
-	_log 1 "${FUNCNAME[0]}: _DEBUG=${_DEBUG}"
+	_log 0 "${FUNCNAME[0]}: _LOG=${_LOG}"
+	_log 0 "${FUNCNAME[0]}: _SILENT=${_SILENT}"
+	_log 0 "${FUNCNAME[0]}: _DEBUG=${_DEBUG}"
 	return
 }
 
@@ -344,33 +369,60 @@ _backup() {
 }
 
 _format() {
-	_findInsertedUsbDisk || _log 4 "no new usable usb disk found"
-	echo -n "is ${yellow}$_newInsertedUsbDisk${reset} the one? [Y/n] "
-	read -r -s -t 10 -n 1 _YES
-	if [[ ${_YES} != "Y" ]]; then
-		_log 4 "user exited"
+	_findNewDisk || _log 4 "no new disk found" && _log 1 "found ${_newDiskDevice}"
+	_printDiskInfo "${_newDiskDevice}"
+	_prompt "is ${green}${_newDiskDevice}${reset} the desired disk? [type YES to proceed] "
+	read -r -s -t 10 -n 3 _YES ; echo
+	if [[ "${_YES}" != "YES" ]]; then
+		_log 4 "uppercase YES is required, try again"
 	fi
-	local _newDsinkDisk="/dev/${_newInsertedUsbDisk}"
+	local _newDsinkDisk="${_newDiskDevice}"
 	local _newDsinkDiskPartition="${_newDsinkDisk}1"
-	findmnt ${_newDsinkDiskPartition} && _log 4 "${_newDsinkDiskPartition} is MOUNTED"
+	#findmnt ${_newDsinkDiskPartition} && _log 4 "${_newDsinkDiskPartition} is MOUNTED"
 	# since we're going to reformat this device, we should wipe it before
 	# either wipefs -a /dev/sdX
 	# wipefs --all --backup /dev/sdX
 	# or dd if=/dev/zero of=/dev/sdX bs=512 count=1 conv=notrunc
 	sudo wipefs --all --backup ${_newDsinkDisk} &>/dev/null || _log 4 "ERROR"
-	echo "erased the partiton table; writing new label now"
+	_log 1 "erased the partiton table on ${_newDsinkDisk}; writing new label now"
+	#echo "erased the partiton table; writing new label now"
 	until ls ${_newDsinkDisk} &>/dev/null; do
 		sleep 1
 		echo "waiting on ${_newDsinkDisk}"
 	done
 	sudo parted -s ${_newDsinkDisk} mklabel gpt
+	_getPTUUID ${_newDsinkDisk}
 	sudo parted -s ${_newDsinkDisk} mkpart dsink 1 100%
+	exit
 	# note: waiting on devices is tricky
 	# using:
 	# watch -n0.1 -be ls -l /dev/sda1
 	# but the easiest fix is to sleep to let the kernel repopulate the device file
-	sleep 1
+	#set -x
+	#_counter=10
+	#while [ $_counter -gt 0 ]; do
+	#	if ! _PTUUID=$(_getPTUUID $_newDsinkDisk); then
+	#		echo -n "[waiting on $_newDsinkDisk ; $_counter of 5"
+	#		((_counter--))
+	#		sleep 1
+	#	else
+	#		_counter=0
+	#	fi
+	#done
+	#_counter=5
+	until [ $(stat -c "%G" ${_newDsinkDisk}) = "disk" ]; do
+		echo "waiting on ${_newDsinkDisk}..."
+	done
 	sudo cryptsetup luksFormat --verify-passphrase --batch-mode ${_newDsinkDiskPartition}
+	#while [ $_counter -gt 0 ]; do
+	#	if ! sudo cryptsetup luksFormat --verify-passphrase --batch-mode ${_newDsinkDiskPartition}; then
+	#		echo "[waiting on $_newDsinkDisk ; $_counter "
+	#		((_counter--))
+	#		#sleep 1
+	#	else
+	#		_counter=0
+	#	fi
+	#done
 	sudo cryptsetup luksOpen ${_newDsinkDiskPartition} dsink
 	until ls /dev/mapper/dsink 2>/dev/null; do
 		echo -n "waiting on /dev/mapper/dsink"
@@ -386,46 +438,284 @@ _status() {
 }
 
 _test() {
-	# function for use in testing things during development
-	_isBlockDevice $_workingParams && echo BLOCK || echo NOT BLOCK
-	set -x
-	#_PTUUID=$(_getPTUUID $_workingParams) || echo "NOPE"
-	_getPTUUID $_workingParams
-	_getBlockType $_workingParams
-	echo "TEST "
-	exit 0
+	# convenient function for use in testing things during development
+	_isDeviceReady $_workingParams || _log 4 "${_workingParams} is not ready"
+	_isBlockDevice $_workingParams
+	#_findNewDisk || _log 4 "no new disk found" && _log 1 "found ${_newDiskDevice}"
+	#_isBlockDevice $_workingParams && echo BLOCK || echo NOT BLOCK
 }
 
 _isBlockDevice() {
-	# arg1 = whole disk device to check (eg sda)
+	# arg1 = disk device to check (eg /dev/sda)
 	# return 0 if true, 1 if false
-	#[ -b /dev/${1:-null} ] || return 1
-	[ -b /dev/${1:-null} ]
+	[ -b ${1:-null} ]
 }
 
-_getBlockType() {
-	# arg1 = whole disk device (eg sda)
-	# return (echo) the disk type reported by lsblk
-	local _diskType=$(lsblk -oTYPE /dev/${1})
-	echo $_diskType
+_isDeviceReady() {
+	# a little hacky way of waiting on the disk before probing
+	# arg1 = disk device to check (eg /dev/sda)
+	# checks for group=disk (which seems to be necessary)
+	# NOTE: this function will hang indefinitely if the deivce never appears
+	_isBlockDevice $1 || return 1
+	until [ $(stat -c "%G" ${1}) = "disk" ]; do
+		sleep 0.1
+	done
+	_isDeviceWritable $1 || _log 4 "device $1 not writable"
+	_getPartitionList $1 &>/dev/null || _log 4 "no partitions detected on $1"
+	return 0
+}
+
+_isDeviceWritable() {
+	if stat -c "%a" $1 | grep ".[67.]" &>/dev/null; then
+		return 0
+	else
+		return 1
+	fi
 }
 
 _getPTUUID() {
-	# ARG1 = sd device (eg sda)
+	# ARG1 = sd device (eg /dev/sda)
 	# the PTUUID is cataloged into dsink.disks at the time of format
 	# return 1 if no device or not block
 	# return 2 if no PTUUID found
 	# echo the whole disk partition table UUID if found
-	local _rawDevice=${1}
-	_isBlockDevice $_rawDevice || return 1
-	local _PTUUID=$(lsblk -Sn -oPTUUID /dev/${_rawDevice} 2>/dev/null)
+	#local _rawDevice=${1}
+	#_isBlockDevice $_rawDevice || return 1
+	local _PTUUID=$(lsblk -Sn -oPTUUID ${1} 2>/dev/null)
 	if [ -z "$_PTUUID" ]; then
-		return 2
+		return 1
 	else
 		echo "$_PTUUID"
 	fi
 }
+
+_isDiskDsink() {
+	# arg 1 = disk device (/dev/sda)
+	# if PTTYPE = gpt
+	# if partition 1 PARTLABEL = dsink
+	# return 0 if true, 1 if disk is not a dsink device (must have 1 part labeled
+	# dsink)
+	if [[ $(lsblk -nS -oPTTYPE ${1}) == "gpt" ]]; then
+		if [[ $(lsblk -n -oPARTLABEL ${1}1) == "dsink" ]]; then
+			return 0
+		else
+			return 1
+		fi
+	else
+		return 1
+	fi
+}
+
+_findMounts() {
+	_devicePartitionList=$(_getPartitionList ${1}) || return 1
+	_t=5000
+	declare -A _parts
+	for p in ${_devicePartitionList}; do
+		_device=/dev/${p}
+		if _p_status=$(findmnt -n -oTARGET $_device); then
+			_parts[${_device}]=${_p_status}
+		else
+			findmnt --poll=mount --first-only --timeout=${_t} ${_device} &>/dev/null &
+			_parts[${_device}]=$!
+		fi
+	done
+	wait
+	for m in "${!_parts[@]}"; do
+		if [[ "${_parts[${m}]}" == /* ]]; then
+			findmnt -S ${m} -oSOURCE,SIZE,AVAIL,USED,USE%,TARGET
+		elif [[ "${_parts[${m}]}" =~ ^[0-9] ]]; then
+			if _m_check=$(findmnt -n -oTARGET $m); then
+				findmnt -S ${m} -oSOURCE,SIZE,AVAIL,USED,USE%,TARGET
+			else
+				echo "$m ${yellow}unmounted${reset}"
+			fi
+		else
+			_log 4 "${m} did not return an expected value "
+		fi
+	done
+}
+
+
+__findMounts() {
+	# arg 1 = whole disk device (eg /dev/sda)
+	# find the number of partitions
+	_devicePartitionList=$(_getPartitionList ${1}) || _log 4 "no device partition list"
+	# define how long findmnt will wait on a device until it gives up
+	_t=5000
+	# make into a bash array
+	declare -A _parts
+	for p in ${_devicePartitionList}; do
+		_device=/dev/${p}
+		findmnt --poll=mount --first-only --timeout=$_t $_device &>/dev/null &
+		_parts[$_device]=$!
+	done
+	for part in "${!_parts[@]}"; do
+		wait ${_parts[$part]}
+		if findmnt -S $part &>/dev/null; then
+			_parts[${part}]=true
+		else
+			_parts[${part}]=false
+		fi
+	done
+	for m in "${!_parts[@]}"; do
+		if [[ "${_parts[${m}]}" = "false" ]]; then
+			echo "$m ${yellow}unmounted${reset}"
+		else
+			findmnt -S ${m} -oSOURCE,SIZE,AVAIL,USED,USE%,TARGET
+		fi
+	done
+	# not how i would like this to work, but it works mostly
+	# the problem is if there is one non-mounting partition, it waits as long as
+	# the _timer is set since we wait on all findmnt -poll commands
+	# i don't know how better to optimize this now
+}
+
+_waitForMounts() {
+	# arg 1 = disk name (eg sda)
+	# find the partitions of a disk
+	_devicePartitionList=$(ls /sys/block/${1}/*/partition | cut -f5 -d/ | tr '\n' ' ')
+	_t=5000
+	for part in ${_devicePartitionList}; do
+		findmnt --poll=mount --first-only --timeout=$_t /dev/$part &>/dev/null &
+	done
+	wait
+}
+
+_printMountInfo() {
+	# job: discover and print filesystem details of specified whole disk
+	# filesystem, mount state, and if empty
+	# arg 1 = whole disk device file (eg /dev/sda)
+	_partList=$(_getPartitionList "${1}") || _log 4 "no partitions"
+	_log 1 "partitions on ${_dev}: ${_partList}"
+}
+
+_getPartitionList() {
+	# for a given disk, discover how many partitions
+	# return the list (eg 'sda1 sda2')
+	# return 1 if none or error
+	# arg 1 = whole disk device file
+	_x=$(lsblk -n -l "${1}" | tail -n +2 | cut -f1 -d' ' | tr '\n' ' ')
+	if [ -z "${_x}" ]; then
+		return 1
+	else
+		echo "${_x}"
+	fi
+}
+
+# spec
+# function findMounts
+# run against all partitions of whole disk
+# get partition list, put into assoc array as keys
+# for each, run findmnt
+# if mounted, insert the mountpoint as value for the key
+# if not mounted, run findmnt --poll in background and put pid as key
+# wait on the findmnt poll
+# check with findmnt once more
+# if nothing, replace the pid with UNKNOWN
+# pass back as a global VAR...
+
+# spec
+# function printMounts
+# call findMounts, use global var
+# for moounted, print fs + util info and whether empty or not
+# for unmounted, print fs
+# look for dsink partition tag
+
+_printDiskInfo() {
+	# arg1 = whole disk device file (ie /dev/sda)
+	# get device info and print it in human readable form
+	_dev=${1##*/}
+	#_isBlockDevice $1 || _log 4 "$1 is not a block device"
+	_isDeviceReady $1 || _log 4 "$1 is not ready"
+	_isDeviceWritable $1 || _log 4 "$1 is not writable"
+	udevadm settle
+	echo -e "\n==============PHYSICAL:========================================"
+	lsblk -S -oNAME,SIZE,VENDOR,PTTYPE,PTUUID ${1}
+	echo -e "\n==============LOGICAL:========================================="
+	# TODO: this fails if there are no partitions!
+	lsblk -oNAME,SIZE,PARTLABEL,FSTYPE,UUID ${1} 
+	echo -e "\n==============STATE:==========================================="
+	if _isDiskDsink "${1}"; then
+		_checkMount && _log 3 "dsink mounted...${1}...i think"
+		if _PTUUID=$(_getPTUUID ${1}); then
+			_log 1 "${1} is a dsink disk: ${_PTUUID}"
+			_log 1 "check catalog to confirm: dsink disk ${_PTUUID:0:3}"
+			return 0
+		else
+			_log 2 "${1} looks like a dsink disk, but has no PTUUID"
+			echo "require some override here"
+			return 1
+		fi
+	fi
+	_findMounts "${1}"
+	echo
+	#findmnt -S ${m} -oSOURCE,SIZE,AVAIL,USED,USE%,TARGET
+}
 	
+
+_irishExit() {
+	echo -ne "\r${yellow}WARNING${reset}: to retry, press R, to quit, press ENTER\n"
+	read -s -t 15 -n 1 _ANS
+	if [[ ${_ANS:-n} = 'R' ]]; then
+		return
+	else
+		_log 4 "user requested exit with ctrl-c"
+	fi
+}
+
+_findNewDisk() {
+	# job: look at devices before, prompt user to insert new disk, identify the
+	# newly inserted disk, then set the name of the device (eg /dev/sda) as a
+	# global VAR=/dev/sda
+	# return 1 if no new disks found
+	# no args taken
+	# naturally interactive...requires user engagement
+	# NOTE: _SILENT=true must be ignored for this function...need to resolve this,
+	# although it still works in silent mode since no user key input is required
+	# NOTE: because this is interactive, we cannot pass the value back with echo
+	# AND interact with the user since it would require a subshell...which waits
+	# on the command (function) to complete before the output is set...ie, we need
+	# to use a global VAR to pass the one result (the device file name) back.
+	# the method is not ironclad...but it works by watching the /sys/block
+	# namespace for changes.
+	local _usbDisksBefore=($(ls /sys/block))
+	local _countBefore=${#_usbDisksBefore[@]}
+	local _usbDisksAfter
+	local _countAfter
+	local _newInsertedUsbDisk
+	declare -g _newDiskDevice
+	local _attempts=3
+	_log 1 "insert usb drive now...hit CTRL-C to exit"
+	trap _irishExit SIGINT
+	while [ ${_attempts} -gt 0 ]; do
+		_log 1 "looking for new device..."
+		if watch -n 0.1 -g ls /sys/block &>/dev/null; then
+			_usbDisksAfter=($(ls /sys/block))
+			_countAfter=${#_usbDisksAfter[@]}
+			if [[ ${_countAfter} -gt ${_countBefore} ]]; then
+				break
+			elif [[ ${_countAfter} -lt ${_countBefore} ]]; then
+				_log 3 "device disappeared...insert new device now"
+				# re-gather the device list
+				_usbDisksBefore=($(ls /sys/block))
+				((_countBefore--))
+				((_attempts--))
+			fi
+		fi
+	done
+	_log 0 "block devices before: [${#_usbDisksBefore[@]}] '${_usbDisksBefore[@]}'" 
+	_log 0 "block devices after: [${#_usbDisksAfter[@]}] '${_usbDisksAfter[@]}'" 
+	# determine the new device by comparing before and after lists
+	[[ ${_countBefore} == ${_countAfter} ]] && return 1
+	for i in "${_usbDisksAfter[@]}"; do
+		skip=
+		for x in "${_usbDisksBefore[@]}"; do
+			[[ $i == $x ]] && { skip=1; break; }
+		done
+			[[ -n $skip ]] || _newInsertedUsbDisk=$i
+	done
+	_newDiskDevice="/dev/${_newInsertedUsbDisk}"
+}
 
 _findInsertedUsbDisk() {
 	# to be run when new usb device needs to be found
@@ -447,8 +737,11 @@ _findInsertedUsbDisk() {
 			echo -e "\nuser exited"; exit 1
 		elif [[ ${_KEY} = "" ]]; then
 			echo -e "\nsearching for new drive now..."
+			#until [[ $(watch -n 0.1 -g ls /sys/block &>/dev/null) = 0 ]]; do
+			#	echo "waiting on new device"
+			#done
 			# the sleep here gives the kernel time to add the device
-			sleep 9
+			#sleep 2
 			# NOTE: SEAGATE SPINNING DISK TAKES A LONG TIME...10 seconds is needed!
 			_usbDisksAfter=($(ls /sys/block | grep ^sd))
 			_newDeviceCount=$((${#_usbDisksAfter[@]}-${#_usbDisksBefore[@]}))
@@ -470,8 +763,8 @@ _findInsertedUsbDisk() {
 			[[ -n $skip ]] || _newInsertedUsbDisk=$i
 	done
 	_deviceFile="/dev/${_newInsertedUsbDisk}"
+	_isBlockDevice ${_deviceFile} || _log 4 "${_deviceFile} is not a block device"
 	_devicePartitionList=$(ls ${_deviceFile}? | tr '\n' ' ')
-	_isBlockDevice ${_deviceFile} && echo ERRRRRRRRRRRRRROR 
 	ls ${_deviceFile}?
 	#
 	# NEED TO make more robust...ie if there are no partitions
