dotfi save by jason on delphi

diff --git a/bin/germ b/bin/germ
--- a/bin/germ
+++ b/bin/germ
@@ -59,10 +59,13 @@ label=$(tput setab 7; tput setaf 0)
 _studioDirName=studiodev
 _studioDir="$(dirname ~/.)/${_studioDirName}"
 # GERM lives inside studio (the master container)
-_germDirName=germ1
+_germDirName=germ
 _germDir="${_studioDir}/${_germDirName}"
 _germGitDisk="${_germDir}/.gitdisk"
 _logFile="${_germDir}/germ.log"
+# SET GIT COMMANDS for convenience and consistency
+_git="git --git-dir=${_germGitDisk} --work-tree=${_germDir}"
+# NOTE, future use may involve setting work-tree differently or locally
 
 # global variables we use
 self=$(basename $0)
@@ -356,8 +359,8 @@ _getCreateOptions() {
 # SUB COMMANDS
 
 __list() {
-	local _gitdir="${_germGitDisk}"
-	local _git="git --git-dir=${_gitdir}"
+	#local _gitdir="${_germGitDisk}"
+	#local _git="git --git-dir=${_gitdir}"
   { ${_git} rev-list --objects --all
   ${_git} rev-list --objects -g --no-walk --all
   ${_git} rev-list --objects --no-walk \
@@ -368,24 +371,31 @@ __list() {
 }
 
 _status() {
-	local _gitdir="${_germGitDisk}"
-	local _git="git --git-dir=${_gitdir}"
+	#local _gitdir="${_germGitDisk}"
+	#local _git="git --git-dir=${_gitdir}"
 	_log 1 "studio dir name: ${_studioDirName}"
 	_log 1 "studio path: ${_studioDir}"
 	_log 1 "germ path: ${_germDir}"
 	_log 1 "germ gitdisk: ${_germGitDisk}"
-	_log 1 "'git fsck'"
-	${_git} fsck
+	_log 1 "'git fsck --full'"
+	${_git} fsck --full
+	#_log 1 "'git fsck --unreachable'"
+	#${_git} fsck --unreachable
 	#_log 1 "'git reflog'"
 	#${_git} reflog
-	_log 1 "'git log --graph --reflog'"
+	#_log 1 "'git log --graph --reflog'"
 	${_git} log --graph --reflog
-	
+	# the above runs into a pager and is quite nice and useful already
+	# the below is someone else's custom formatting
+# $ git config --global alias.graph \
+#  "log --graph --all --format='%h %s%n        (%an, %ar)%d' --abbrev-commit"
+	_log 2 "check out the 'git gc' command...does it leave stats?"
+	_isIndexClean || _log 3 "INDEX IS DIRTY" && _log 1 "INDEX CLEAN"
+	#_readBlob bb10
+	#_recover
 }
 
 _list() {
-	local _gitdir="${_germGitDisk}"
-	local _git="git --git-dir=${_germGitDisk}"
 	_log 1 "git 'ls-files -s'"
 	${_git} ls-files -s $_workingParams
 	# HACKED now
@@ -471,7 +481,150 @@ _list() {
 #			j/atomic/key.commit
 # check for consistency each time
 
+# TODO: question: define line limit or not?  bash arrays have none
+# read blob
+_readBlob() {
+	# arg 1 = blob ID
+	# read a blob into a bash array
+	# export the array into the global environment
+	local _blobID=$1
+	${_git} cat-file -e ${_blobID} &>/dev/null || return 1
+	readarray -t _blobArray < <(${_git} cat-file -p ${_blobID})
+	if [ ${#_blobArray[@]} -ne 0 ]; then
+		_log 1 "read blob ${_blobID:0:5}"
+		_log 1 "found ${#_blobArray[@]} line[s] in the new blob"
+		export _blobArray
+	else
+		_log 3 "${_blobID} is empty"
+		return 1
+	fi
+}
+
+######################
+# INDEX MANIPULATION
+
+_mapPrimaryKey() {
+	# arg 1 = primary key (unix seconds)
+	# arg 2 = blobID
+	# assumes global _blobArray
+	# TODO add some sanity checks here
+	local _key=$1
+	local _blobID=$2
+	local year=$(date -d @${1} +"%Y")
+	local month=$(date -d @${1} +"%m")
+	local day=$(date -d @${1} +"%d")
+	local _keyPath="a/$year/$month/$day/${_key}"
+	# UPDATE the index (ie maps blob to namespace...hashed date - key is seconds)
+	${_git} update-index --add --cacheinfo 10064,$_blobID,${_keyPath}
+	_log 1 "added ${_blobID} as ${_keyPath}"
+}
+
+_mapBlob() {
+	# arg 1 = path
+	# arg 2 = blobID
+	[ $# -eq 0 ] && return 1
+	local _path="${1}"
+	local _blobID=${2}
+	${_git} update-index --add --cacheinfo 10064,$_blobID,"${_path}"
+	_log 1 "mapped ${_blobID:0:5} as ${_path}"
+}
+
+_mapFirstLine() {
+	# take first line
+	# replace space with dash
+	# add to f/
+	echo "first line processor"
+}
+
+_mapTags() {
+	# arg 1 = key
+	# arg 2 = blobID
+	# check for tags on first line
+	# assumes global _blobArray
+	[ $# -ne 2 ] && return 1
+	local _key="${1}"
+	local _blobID=${2}
+	local _line
+	for _line in "${_blobArray[@]}"; do
+		if [ -z "${_line:-}" ]; then
+			_log 0 "blank line detected..skipping"
+			continue	# ignore blank lines
+		elif [ "${_line:0:1}" = "#" ]; then
+			_log 0 "^# detected, checking for tag"
+			_tag=${_line%% *}
+			if [ -z "${_tag:1}" ]; then
+				_log 0 "empty tag, skipping"
+			else
+ 				_log 0 "found tag '${_tag:1}'"
+				_mapBlob "e/${_tag:1}/${_key}" $_blobID 
+				#${_git} update-index --add --cacheinfo 10064 $_blobID e/${_tag:1}/${_key}
+				_log 1 "mapped ${_blobID:0:5} as ${_key} in tag space e/${_tag:1}"
+			fi
+		fi
+	done
+}
+
+# i had a bug which opened my eyes to an interesting possibility
+# i was adding the whole string (it was _workingParams or _message) as the
+# commit message...which made git log and tig both show the germ itself nicely.
+# i fixed the commit to use the first line instead of the whole message string
+# and now the git log and tig both lost the bug.
+
+
+# commit relies on _blobArray, using the first line as the commit msg
+_doCommit() {
+	# discrete operation...write the index as a commit
+	_log 2 "commit msg= ${_blobArray[0]}"
+	_commitMsg="${_blobArray[0]}"
+	_tree=$(${_git} write-tree)
+	_log 1 "created tree object ${_tree}"
+	# next make sure there is a parent
+	if ${_git} rev-list --max-parents=0 HEAD &>/dev/null; then
+		_parent=$(${_git} rev-list -n1 --all HEAD)
+		_log 1 "found a parent: ${_parent}"
+		_commit=$(${_git} commit-tree $_tree -p $_parent -m "$_commitMsg")
+	else
+		_log 1 "found no parent"
+		_commit=$(${_git} commit-tree $_tree -m "[genesis] ${_commitMsg}")
+	fi
+	_log 1 "created the commit object ${_commit}"
+	${_git} update-ref HEAD "${_commit}"
+	_log 1 "updated the HEAD reference"
+	return 0
+}	
+
+_printCommitMsg() {
+	# assumes global _blobArray
+	_commitMsg="${_blobArray[0]}"
+	echo "${_commitMsg}"
+}
+
 _add() {
+	if [ ${_inline:-null} = "true" ]; then
+		_log 1 "found an inline string: '$_workingParams'"
+		[ -z "${_workingParams}" ] && _log 4 "'add -i' cannot contain an empty message"
+	else
+		_message=$(vipe)
+		_log 0 "vipe-produced entry: $_message"
+		_workingParams="${_message}"
+	fi
+	_log 2 "message: ${_workingParams}"
+	# set up primary key namespace mapping
+	local _key=$(date +%s)
+	local _keyPath="a/$(date +%Y)/$(date +%m)/$(date +%d)/${_key}"
+	# ADD the BLOB...get the BLOB id
+	_blobID=$(${_git} hash-object --stdin -w <<< "${_workingParams}")
+	_log 1 "added the blob to the object store"
+	_readBlob $_blobID 
+	_mapPrimaryKey $_key $_blobID
+	# map first word on first line to d/
+	_firstWord=${_blobArray[0]%% *}
+	_mapBlob "d/${_firstWord}/${_key}" $_blobID
+	_mapTags $_key $_blobID
+	_doCommit
+}
+
+__add() {
 	# $_workingParams contains the string...we need to check if this is null as
 	# some characters (like #) will be stripped out by bash unless we escape it.
 	if [ ${_inline:-null} = "true" ]; then
@@ -485,8 +638,6 @@ _add() {
 	# set up primary key namespace mapping
 	local _key=$(date +%s)
 	local _keyPath="a/$(date +%Y)/$(date +%m)/$(date +%d)/${_key}"
-	# set up git command
-	local _git="git --git-dir=${_germGitDisk}"
 	# ADD the BLOB...get the BLOB id
 	_blobID=$(${_git} hash-object --stdin -w <<< "${_workingParams}")
 	_log 1 "added the blob to the object store"
@@ -494,11 +645,7 @@ _add() {
 	# plus we will parse the blob now to build the metadata view
 	readarray -t _blobArray < <(${_git} cat-file -p ${_blobID})
 	_log 1 "found ${#_blobArray[@]} line[s] in the new blob"
-	# testing multiple lines
-	#_log 1 "added a new line (for testing purposes)"
-	#_blobArray+=("#germ how to catch a hash in the first word")
-	#_log 1 "found ${#_blobArray[@]} line[s] in the new blob"
-	# UPDATES the index (ie maps blob to namespace...hashed date - key is seconds)
+	# UPDATE the index (ie maps blob to namespace...hashed date - key is seconds)
 	${_git} update-index --add --cacheinfo 10064 $_blobID ${_keyPath}
 	_log 1 "added ${_blobID} as ${_keyPath}"
 	# map first word on first line to d/
@@ -518,6 +665,7 @@ _add() {
 		fi
 	done
 	# next create a tree object from the index
+	# THIS IS A DISCRETE OPERATION...put in a function
 	_tree=$(${_git} write-tree)
 	_log 1 "created tree object ${_tree}"
 	# next make sure there is a parent
@@ -582,52 +730,52 @@ _create() {
 
 }
 
-# TODO  TODO  TODO
-# BIG BUG
-# if the add function doesn't complete, something breaks
-#
-# DEBUG: germ: vipe-produced entry: germ
+_isIndexClean() {
+	${_git} diff-index --quiet --cached HEAD -- || return 1
+}
+
+_recover() {
+	# check git status for objects in index not yet committed
+	# we always want the index to match the latest commit...this is an exercise of
+	# automatic repair when an add() operation fails completely
+	# we will also improve the add() function to be more atomic...in the meantime,
+	# this is a programatic way of detecting the blobs and mapped trees we added
+	# but failed to commit
+	local _gitDiff="${_git} --no-pager diff --cached --summary HEAD"
+	local _lastCommit=$(${_git} rev-parse HEAD)
+	_isIndexClean || _log 3 "index is dirty"
+	_inconsistentCount=$(${_gitDiff} | wc -l)
+	#_lostFiles=$(${_gitDiff} #last=${data##*,} 
+	_lostMaps=$(${_gitDiff} | cut -f5 -d' ')
+	_log 2 "last commit id: ${_lastCommit}"
+	_log 2 "inconsistent count: ${_inconsistentCount}"
+	_log 2 "uncommitted files: ${_lostMaps}"
+	_log 3 "to recover, write tree, find parent, commit tree, update HEAD"
+	local _lostKeys=()
+	for _map in ${_lostMaps}; do
+		_lostKeys+=(${_map##*/})
+	done
+	printf '%s\n' "${_lostKeys[@]}" | sort | uniq
+	# possibility of multiples
+	# sort by unix seconds key
+	# cat-file for first line (the commit message)
+	# get
+	_log 0 "remove the d/ map in the index first"
+	#${_git} update-index --remove --cacheinfo 10064,$_blobID,d/${_tag:1}/${_key}
+	#${_git} rm --cached a/2023/01/30/1675145248
+	#${_git} rm --cached d/germ/1675145248	
+	# DONE BY HAND
+	#_mapPrimaryKey 1675145105 bb10ac176fb1a38211c0c26d3c57c23abd1ab9f6
+	_readBlob bb10ac176fb1a38211c0c26d3c57c23abd1ab9f6
+	_mapTags 1675145105 bb10ac176fb1a38211c0c26d3c57c23abd1ab9f6
+	_printCommitMsg
+	_doCommit
+}
+
+
 # 
-# the filter that looks for tags
-# 
-# #
-# 
-# can't be fooled
-# INFO: germ: added the blob to the object store
-# INFO: germ: found 7 line[s] in the new blob
-# 
-# INFO: germ: added ad0e593e48fdbe466889e7aa1c6edcdba8937132 as a/2023/01/30/1675145248
-# INFO: germ: mapped ad0e5 as 1675145248 in d/germ
-# DEBUG: germ: found tag ''
-# error: Invalid path 'e//1675145248'
-# fatal: git update-index: --cacheinfo cannot add e//1675145248
-# jason delphi ~ d=o $ germ -d list
-# <this returned nothing>
-#
-# where as normally, we do this:
-# INFO: germ: created tree object b4a8e649fdde149141ed8d327f25c414e680cf48
-# INFO: germ: found a parent: 7c3294b2649623223a8cc83948c05a298d37dd5a
-# INFO: germ: created the commit object f32863ce9c8c55a3db7cb60343092cc18ac547fa
-# INFO: germ: updated the HEAD reference
-# 
-# see that the final tree, locate parent, commit, and move HEAD
-# did not complete...leaving the database in an inconsistent state
-#
-#
-# note, the code tried to set a tag to '', then tried to update the index with
-# an invalid path e//167...
-# which left the add() function incomplete
-# need to add traps to the write to make it more safe
-# need also a way to rebuild the correct manhole interface
-# right now this instance is broken...and i need to figure out the git status
-# and the commands to recover and build them into a repair function for when a
-# write doesn't complete and leaves the index wonky.
-#
-#
-# the blob wrote, recorded in a/ and d/germ as bb10a
-# but no new tree or commit objects
-# so we should be able to find blobs not referenced in the commit
-# 
+# TODO also capture the git errors...this is being lost now
+# and set -x is the only means of capturing the break
 
 _irishExit() {
   echo -ne "\r${yellow}WARNING${reset}: ctrl-c detected; to resume, press R, to quit, press ENTER\n"
